blogapp/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('search.urls')),
    path('', include('main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from .views import home, post, detail, delete, update, my_post


# router links
urlpatterns = [
    path('', home, name='home'),
    path('post/', post, name='post'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('update/<int:pk>/', update, name='update'),
    path('mypost/', my_post, name='mypost'),
]

search/urls.py
from django.urls import path

from .views import searchposts

# app_name = 'search'

urlpatterns = [
	path('search/', searchposts, name='searchposts'),
]    

main/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Post(models.Model):
    author = models.ForeignKey(User, default=1, related_name="user_post", on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)


    def __str__(self):
    	return self.title
    
    class Meta:
        ordering = ('-created_date',)

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    post = models.ForeignKey(Post, related_name="comments", on_delete=models.CASCADE)
    comment = models.CharField(max_length=500, null=True)
    date_added = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.comment


    def num_comments(self):
        return self.comment_set.all().count()

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from django.db.models import Q
from main.models import Post

# Create your views here.


def searchposts(request):
    if request.method == 'GET':
        query= request.GET.get('q')

        submitbutton= request.GET.get('submit')

        if query is not None:
            lookups= Q(title__icontains=query) | Q(text__icontains=query)

            results= Post.objects.filter(lookups).distinct()

            context={
                'results': results,
                'submitbutton': submitbutton,
               }

            return render(request, 'search.html', context)

        else:
            return render(request, 'search.html')

    else:
        return render(request, 'search.html')

templates/base.html
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <title>{% block title %}BLOGLIT{% endblock %}</title>
    </head>
    <body class="bg-light">
        <div class="container" style="max-width:1000">
            <div class="card shadow-sm" style="margin-top: 20px">
                <div class="card-header">
                    <h6 style="margin-bottom: 0; margin-top: 7; display: inline-block">
                        <a href="/" class="text-dark">BLOGLIT</a>
                    </h6>
                    <span style="float: right">
                        <span class="csqa-nav">
                            <form class=" form-signin d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" action="{% url 'searchposts' %}" method="GET" value="{{request.GET.q}}"> 
                                <input type="text" class="form-control" name="q" value="{{request.GET.q}}" placeholder="Search posts"/> 
                                <input class="btn btn-primary btn-sm mt-1 mb-1" type="submit" name="submit" value="Search"/>
                            </form>
                            {% if user.is_authenticated %}
                            <a href="/mypost/" class="text-dark">My Posts</a> |                        
                            <a href="/post/" class="text-dark" style="display: inline-block">
                                New Post
                            </a>
                            {% endif %}
                        </span>
                    </span>
                </div>
                <div class="pb-2 pt-4 pr-4 pl-4">
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
        <div class="container text-right" style="max-width:1000; padding-right:21; padding-top:2; font-size:14; color: #6c757d; margin-bottom: 7px;">
                <a href="/" class="text-secondary">Home</a> | 
            {% if user.is_authenticated %}
                <a href="/logout" class="text-secondary">Log out ({{user.username}})</a> | 
            {% else %}
                <a href="/login" class="text-secondary">Sign up / log in</a> | 
            {% endif %}
                <a href="https://github.com/akanmu01/blog" class="text-secondary" target="_blank">Source code</a> | 
            <a href="/about" class="text-secondary">About</a>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    </body>
</html>

templates/detail.html
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>{% block title %} {{ post.title }} {% endblock title %}</title>
    </head>
    <body class="bg-light">
        <div class="container" style="max-width:1000">
            <div class="card shadow-sm" style="margin-top: 20px">
                <div class="card-header">
                    <h6 style="margin-bottom: 0; margin-top: 7; display: inline-block">
                        <a href="/" class="text-dark">BLOGLIT</a>
                    </h6>
                    <span style="float: right">
                        <span class="csqa-nav">
                            <form class=" form-signin d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" action="{% url 'searchposts' %}" method="GET" value="{{request.GET.q}}"> 
                                <input type="text" class="form-control" name="q" value="{{request.GET.q}}" placeholder="Search posts"/> 
                                <input class="btn btn-primary btn-sm mt-1 mb-1" type="submit" name="submit" value="Search"/>
                            </form>
                            {% if user.is_authenticated %}
                            <a href="/mypost/" class="text-dark">My Posts</a> |                        
                            <a href="/post/" class="text-dark" style="display: inline-block">
                                New Post
                            </a>
                            {% endif %}
                        </span>
                    </span>
                </div>
                <div class="pb-2 pt-4 pr-4 pl-4">
                  <div class="container">
                    <h5>{{ post.title }}</h5>
                    <div style="margin-bottom: 5px; font-size: 17px; white-space: break-spaces">{{ post.text|linebreaksbr}}</div>
                    <div class='text-secondary' style="font-size: 14px">
                      posted by {{ post.author }}</span><span class="separator">|</span> {{ post.created_date }}
                  </div>
                  {% if user.is_authenticated %}
                    {% if user.id == post.author.id %}
                    <p class="blog-post-meta"> 
                      <a class="btn btn-success btn-sm mt-1 mb-1" href="/update/{{ post.pk }}">Update</a>
                      <!-- Button trigger modal -->
                      <button type="button" class="btn btn-danger btn-sm mt-1 mb-1" data-toggle="modal" data-target="#exampleModal">
                        Delete
                      </button>

                      <!-- Modal -->
                      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog">
                          <div class="modal-content">
                            <div class="modal-header">
                              <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to delete this post</h5>
                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            <div class="modal-body">
                              <a class="btn btn-danger btn-sm mt-1 mb-1" href="/delete/{{ post.pk }}">Delete</a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </p> 
                    {% endif %}
                  {% endif %}
                  <p id="comment" >Comments: {{ post.comments.count }}</p><hr>
                  {% for cmt in post.comments.all %}
                    <div>
                      <div class="answer-block">
                        <div class="answer-text">{{ cmt.comment|linebreaks }}</div>
                        <div class="text-secondary answer-sub">
                          <span>{{ cmt.user.username }}</span>
                          <span class="separator">|</span>
                          <span>{{ cmt.date_added }}</span>
                        </div>
                      </div>
                    </div>
                  {% empty %}
                    <p>No comments here yet ! !! !!!</p>
                  {% endfor %}
                  <form method="POST" class="post-form">
                  {% csrf_token %}
                    {{ form.as_p }}
                  <button type="submit" class="btn btn-primary">Add Comment</button>
                  </form>
                  <a href="/">&laquo; Go Back</a>  
                </div>
                <style type="text/css">
                  #id_comment{
                    width: auto;
                  }
                </style> 
              </div>
            </div>
        </div>
        <div class="container text-right" style="max-width:1000; padding-right:21; padding-top:2; font-size:14; color: #6c757d; margin-bottom: 7px;">
                <a href="/" class="text-secondary">Home</a> | 
            {% if user.is_authenticated %}
                <a href="/logout" class="text-secondary">Log out ({{user.username}})</a> | 
            {% else %}
                <a href="/login" class="text-secondary">Sign up / log in</a> | 
            {% endif %}
                <a href="https://github.com/akanmu01/blog" class="text-secondary" target="_blank">Source code</a> | 
            <a href="/about" class="text-secondary">About</a>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    </body>
</html>

templates/index.html
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <title>{% block title %}BLOGLIT{% endblock %}</title>
    </head>
    <body class="bg-light">
        <div class="container" style="max-width:1000">
            <div class="card shadow-sm" style="margin-top: 20px">
                <div class="card-header">
                    <h6 style="margin-bottom: 0; margin-top: 7; display: inline-block">
                        <a href="/" class="text-dark">BLOGLIT</a>
                    </h6>
                    <span style="float: right">
                        <span class="csqa-nav">
                            <form class=" form-signin d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" action="{% url 'searchposts' %}" method="GET" value="{{request.GET.q}}"> 
                                <input type="text" class="form-control" name="q" value="{{request.GET.q}}" placeholder="Search posts"/> 
                                <input class="btn btn-primary btn-sm mt-1 mb-1" type="submit" name="submit" value="Search"/>
                            </form>
                            {% if user.is_authenticated %}
                            <a href="/mypost/" class="text-dark">My Posts</a> |                        
                            <a href="/post/" class="text-dark" style="display: inline-block">
                                New Post
                            </a>
                            {% endif %}
                        </span>
                    </span>
                </div>
                <div class="pb-2 pt-4 pr-4 pl-4">
                  {% for post in posts %}
                    <h4 class="blog-post-title">{{ post.title }} { <a href="#"> {{ post.author.username }} </a> } </h4>

                    <a>{{ post.comments.count }} comments</a>
                    {% if user.is_authenticated %}

                    <blockquote class="container-fluid">
                    <a href="/detail/{{post.pk}}">Continue reading</a>
                    </blockquote>
                    {% else %}
                      <p><a href="/login/">Login</a> to comment</p>
                    {% endif %}
                  {% endfor %}
                </div>
            </div>
        </div>
        <div class="container text-right" style="max-width:1000; padding-right:21; padding-top:2; font-size:14; color: #6c757d; margin-bottom: 7px;">
                <a href="/" class="text-secondary">Home</a> | 
            {% if user.is_authenticated %}
                <a href="/logout" class="text-secondary">Log out ({{user.username}})</a> | 
            {% else %}
                <a href="/login" class="text-secondary">Sign up / log in</a> | 
            {% endif %}
                <a href="https://github.com/akanmu01/blog" class="text-secondary" target="_blank">Source code</a> | 
            <a href="/about" class="text-secondary">About</a>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    </body>
</html>

templates/my_post.html
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <title>{% block title %}BLOGLIT{% endblock %}</title>
    </head>
    <body class="bg-light">
        <div class="container" style="max-width:1000">
            <div class="card shadow-sm" style="margin-top: 20px">
                <div class="card-header">
                    <h6 style="margin-bottom: 0; margin-top: 7; display: inline-block">
                        <a href="/" class="text-dark">BLOGLIT</a>
                    </h6>
                    <span style="float: right">
                        <span class="csqa-nav">
                            <form class=" form-signin d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" action="{% url 'searchposts' %}" method="GET" value="{{request.GET.q}}"> 
                                <input type="text" class="form-control" name="q" value="{{request.GET.q}}" placeholder="Search posts"/> 
                                <input class="btn btn-primary btn-sm mt-1 mb-1" type="submit" name="submit" value="Search"/>
                            </form>
                            {% if user.is_authenticated %}
                            <a href="/mypost/" class="text-dark">My Posts</a> |                        
                            <a href="/post/" class="text-dark" style="display: inline-block">
                                New Post
                            </a>
                            {% endif %}
                        </span>
                    </span>
                </div>
                <div class="pb-2 pt-4 pr-4 pl-4">
                    <p>
				        <a href="#">{{ post.title }} <span class="text-secondary num-answers">({{  post.comments.count }} comments)</span></a>
				    </p>
                </div>
            </div>
        </div>
        <div class="container text-right" style="max-width:1000; padding-right:21; padding-top:2; font-size:14; color: #6c757d; margin-bottom: 7px;">
                <a href="/" class="text-secondary">Home</a> | 
            {% if user.is_authenticated %}
                <a href="/logout" class="text-secondary">Log out ({{user.username}})</a> | 
            {% else %}
                <a href="/login" class="text-secondary">Sign up / log in</a> | 
            {% endif %}
                <a href="https://github.com/akanmu01/blog" class="text-secondary" target="_blank">Source code</a> | 
            <a href="/about" class="text-secondary">About</a>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    </body>
</html>

templates/post_new.html
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <title>{% block title %}BLOGLIT{% endblock %}</title>
    </head>
    <body class="bg-light">
        <div class="container" style="max-width:1000">
            <div class="card shadow-sm" style="margin-top: 20px">
                <div class="card-header">
                    <h6 style="margin-bottom: 0; margin-top: 7; display: inline-block">
                        <a href="/" class="text-dark">BLOGLIT</a>
                    </h6>
                    <span style="float: right">
                        <span class="csqa-nav">
                            <form class=" form-signin d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" action="{% url 'searchposts' %}" method="GET" value="{{request.GET.q}}"> 
                                <input type="text" class="form-control" name="q" value="{{request.GET.q}}" placeholder="Search posts"/> 
                                <input class="btn btn-primary btn-sm mt-1 mb-1" type="submit" name="submit" value="Search"/>
                            </form>
                            {% if user.is_authenticated %}
                            <a href="/mypost/" class="text-dark">My Posts</a> |                        
                            <a href="/post/" class="text-dark" style="display: inline-block">
                                New Post
                            </a>
                            {% endif %}
                        </span>
                    </span>
                </div>
                <div class="pb-2 pt-4 pr-4 pl-4">
					<div class="container">
					 <div class="row">
					    <div class="col-md-6 offset-md-3">
					        <form method="POST">
					            {% csrf_token %}
					            {{ form.as_p }}
					            <button class="btn btn-lg btn-primary btn-block" type="submit">Post</button>
					        </form>   
					    </div>
					  </div>
					</div>
                </div>
            </div>
        </div>
        <div class="container text-right" style="max-width:1000; padding-right:21; padding-top:2; font-size:14; color: #6c757d; margin-bottom: 7px;">
                <a href="/" class="text-secondary">Home</a> | 
            {% if user.is_authenticated %}
                <a href="/logout" class="text-secondary">Log out ({{user.username}})</a> | 
            {% else %}
                <a href="/login" class="text-secondary">Sign up / log in</a> | 
            {% endif %}
                <a href="https://github.com/akanmu01/blog" class="text-secondary" target="_blank">Source code</a> | 
            <a href="/about" class="text-secondary">About</a>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    </body>
</html>

templates/search.html
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <title>{% block title %}BLOGLIT{% endblock %}</title>
    </head>
    <body class="bg-light">
        <div class="container" style="max-width:1000">
            <div class="card shadow-sm" style="margin-top: 20px">
                <div class="card-header">
                    <h6 style="margin-bottom: 0; margin-top: 7; display: inline-block">
                        <a href="/" class="text-dark">BLOGLIT</a>
                    </h6>
                    <span style="float: right">
                        <span class="csqa-nav">
                            <form class=" form-signin d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" action="{% url 'searchposts' %}" method="GET" value="{{request.GET.q}}"> 
                                <input type="text" class="form-control" name="q" value="{{request.GET.q}}" placeholder="Search posts"/> 
                                <input class="btn btn-primary btn-sm mt-1 mb-1" type="submit" name="submit" value="Search"/>
                            </form>
                            {% if user.is_authenticated %}
                            <a href="/mypost/" class="text-dark">My Posts</a> |                        
                            <a href="/post/" class="text-dark" style="display: inline-block">
                                New Post
                            </a>
                            {% endif %}
                        </span>
                    </span>
                </div>
                <div class="pb-2 pt-4 pr-4 pl-4">
					{% if submitbutton == 'Search' and request.GET.q != '' %}
						{% if results %}
						<h1>Results for <b>{{ request.GET.q }}</b></h1>
						<br/><br/>

							{% for result in results %}
								{% for post in results %}
								    <a href="/detail/{{ post.pk }}">{{ result.title  }}</a>
									<p>{{ result.text }} </p>
								{% endfor %}

							<br/>

							{% endfor %}
						{% else %}
							No search results "{{ request.GET.q }}"
						{% endif %}
					{% endif %}
                </div>
            </div>
        </div>
        <div class="container text-right" style="max-width:1000; padding-right:21; padding-top:2; font-size:14; color: #6c757d; margin-bottom: 7px;">
                <a href="/" class="text-secondary">Home</a> | 
            {% if user.is_authenticated %}
                <a href="/logout" class="text-secondary">Log out ({{user.username}})</a> | 
            {% else %}
                <a href="/login" class="text-secondary">Sign up / log in</a> | 
            {% endif %}
                <a href="https://github.com/akanmu01/blog" class="text-secondary" target="_blank">Source code</a> | 
            <a href="/about" class="text-secondary">About</a>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    </body>
</html>

templates/update.html
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <title>{% block title %}BLOGLIT{% endblock %}</title>
    </head>
    <body class="bg-light">
        <div class="container" style="max-width:1000">
            <div class="card shadow-sm" style="margin-top: 20px">
                <div class="card-header">
                    <h6 style="margin-bottom: 0; margin-top: 7; display: inline-block">
                        <a href="/" class="text-dark">BLOGLIT</a>
                    </h6>
                    <span style="float: right">
                        <span class="csqa-nav">
                            <form class=" form-signin d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0" action="{% url 'searchposts' %}" method="GET" value="{{request.GET.q}}"> 
                                <input type="text" class="form-control" name="q" value="{{request.GET.q}}" placeholder="Search posts"/> 
                                <input class="btn btn-primary btn-sm mt-1 mb-1" type="submit" name="submit" value="Search"/>
                            </form>
                            {% if user.is_authenticated %}
                            <a href="/mypost/" class="text-dark">My Posts</a> |                        
                            <a href="/post/" class="text-dark" style="display: inline-block">
                                New Post
                            </a>
                            {% endif %}
                        </span>
                    </span>
                </div>
                <div class="pb-2 pt-4 pr-4 pl-4">
				<h1> Update Post ...</h1>
				    <form method="POST">
				        {% csrf_token %}
				        {{ form.as_p }}
				        <button type="submit" class="btn btn-primary" style="width:100%;">Update</button>
				    </form>
                </div>
            </div>
        </div>
        <div class="container text-right" style="max-width:1000; padding-right:21; padding-top:2; font-size:14; color: #6c757d; margin-bottom: 7px;">
                <a href="/" class="text-secondary">Home</a> | 
            {% if user.is_authenticated %}
                <a href="/logout" class="text-secondary">Log out ({{user.username}})</a> | 
            {% else %}
                <a href="/login" class="text-secondary">Sign up / log in</a> | 
            {% endif %}
                <a href="https://github.com/akanmu01/blog" class="text-secondary" target="_blank">Source code</a> | 
            <a href="/about" class="text-secondary">About</a>
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    </body>
</html>